version: '3.7'

services:
  # ts-node-docker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
  #   volumes:
  #     - ./src:/home/node/app/src
  #     - ./nodemon.json:/home/node/app/nodemon.json
  #   container_name: ts-node-docker
  #   expose:
  #     - '4000'
  #   ports:
  #     - '4000:4000'
  #   links:
  #     - mongo
  #   command: npm run dev
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'